### ISSUE TITLE
restart

### ISSUE THREAD

**Issue by ghamtre** [firekylin/firekylin#405]
is there a method to stop calling domain.com/install/index every time I reset my server?

Thanks

**Comment by ddhhz** [comment]
Please list out detailed steps so we can better understand and reproduce your issue. Thank you!

**Comment by ghamtre** [comment]
I used this guide to install firekylin on Heroku:
https://github.com/firekylin/firekylin/wiki/%E5%AE%89%E8%A3%85
and everything is working fine!

But every time I commit something new to Heroku (restart the server), I get this screen asking me to put my mysql data again:
[https://camo.githubusercontent.com/d980b097f6faa97cccb1afa301c41c3793d805a5/687474703a2f2f70302e7168696d672e636f6d2f743031323133383132613032613462383935382e706e67](url)

is there a way to deactivated the install process?

**Comment by lizheming** [comment]
Does `app/common/config/db.js` and `.installed` file exist in firekylin path? It seems node have no access to create config file.

**Comment by ddhhz** [comment]
Heroku does not have persistent file storage which means all the files get wiped and code gets freshly built on every since push. 

Since firekylin uses `.installed` and `db.js` files from disk to determine the installation status and db connection info, it simply cannot be run on heroku at this time.

Future considerations: use ENV variables to replace `db.js` and check db instead of `.installed` for installation status.

**Comment by lizheming** [comment]
@ddhhz great!

**Comment by lizheming** [comment]
By the way, if heroku doesn't support storage file permanently, you should not enjoy some firekylin feature depend on storage like upload file in local, edit theme file online at admin dashboard, and upgrade firekylin online. All those feature you should notice.
